// AUTO-GENERATED by scripts/scan.mjs — haath se edit mat karo
window.DASHBOARD_DATA = {
  "demo": false,
  "generatedAt": "Tuesday, 1 September 2026 · 08:58 pm IST",
  "sessionDate": "01/09/2026",
  "nextTradingDay": "Wednesday, 2 September 2026",
  "portfolio": {
    "startCapital": 600000,
    "sizingRule": "Har trade 24% of capital. Exit: +10% pe 50% book, baaki 40 DMA pe trail",
    "sizeByGear": [
      24,
      24,
      24,
      24,
      24
    ]
  },
  "riskRamp": {
    "mode": "full",
    "winningOpen": 4,
    "openCount": 6,
    "need": 2,
    "maxTest": 3,
    "sizePct": 24,
    "note": "4 positions +5% se upar chal rahi hain — market feedback accha hai, full size (24%) pe khelo."
  },
  "strategyTest": {
    "from": "16 Jul 2021",
    "to": "30 Mar 2026",
    "sessions": 1162,
    "capital": 100000,
    "sizeByGear": [
      24,
      24,
      24,
      24,
      24
    ],
    "builtAt": "2026-08-10T18:55:09.533Z",
    "picks": 1395,
    "trades": 368,
    "noTrigger": 454,
    "noCash": 573,
    "wins": 118,
    "losses": 250,
    "winRate": 32.07,
    "avgWin": 19.59,
    "avgLoss": -2.52,
    "expectancy": 4.57,
    "profitFactor": 1.91,
    "avgHold": 12.71,
    "equityGross": 282001,
    "equityNet": 253883,
    "charges": 28118,
    "returnPct": 182,
    "returnNetPct": 153.88,
    "maxDrawdownPct": 13.83,
    "maxConcurrent": 7,
    "maxDeployPct": 99.92,
    "cashDays": 490,
    "curve": [
      {
        "ts": 1626407100,
        "v": 100000
      },
      {
        "ts": 1627357500,
        "v": 100654
      },
      {
        "ts": 1627616700,
        "v": 101238
      },
      {
        "ts": 1628567100,
        "v": 100349
      },
      {
        "ts": 1629171900,
        "v": 97148
      },
      {
        "ts": 1629949500,
        "v": 95878
      },
      {
        "ts": 1631072700,
        "v": 97816
      },
      {
        "ts": 1632109500,
        "v": 97826
      },
      {
        "ts": 1632800700,
        "v": 95816
      },
      {
        "ts": 1633923900,
        "v": 97927
      },
      {
        "ts": 1634787900,
        "v": 99402
      },
      {
        "ts": 1635133500,
        "v": 98672
      },
      {
        "ts": 1636429500,
        "v": 100292
      },
      {
        "ts": 1637552700,
        "v": 98811
      },
      {
        "ts": 1638330300,
        "v": 104068
      },
      {
        "ts": 1639453500,
        "v": 104692
      },
      {
        "ts": 1641181500,
        "v": 103116
      },
      {
        "ts": 1641872700,
        "v": 102920
      },
      {
        "ts": 1642563900,
        "v": 104811
      },
      {
        "ts": 1642995900,
        "v": 102746
      },
      {
        "ts": 1644464700,
        "v": 100101
      },
      {
        "ts": 1644810300,
        "v": 123339
      },
      {
        "ts": 1649648700,
        "v": 129241
      },
      {
        "ts": 1650339900,
        "v": 126295
      },
      {
        "ts": 1651203900,
        "v": 125110
      },
      {
        "ts": 1651722300,
        "v": 130824
      },
      {
        "ts": 1657770300,
        "v": 129495
      },
      {
        "ts": 1658720700,
        "v": 128552
      },
      {
        "ts": 1659584700,
        "v": 128162
      },
      {
        "ts": 1660275900,
        "v": 131716
      },
      {
        "ts": 1662435900,
        "v": 131106
      },
      {
        "ts": 1663127100,
        "v": 130328
      },
      {
        "ts": 1664163900,
        "v": 128358
      },
      {
        "ts": 1665459900,
        "v": 127175
      },
      {
        "ts": 1666928700,
        "v": 124881
      },
      {
        "ts": 1667360700,
        "v": 120978
      },
      {
        "ts": 1667792700,
        "v": 128132
      },
      {
        "ts": 1668138300,
        "v": 128125
      },
      {
        "ts": 1668743100,
        "v": 126979
      },
      {
        "ts": 1669347900,
        "v": 125677
      },
      {
        "ts": 1669866300,
        "v": 124698
      },
      {
        "ts": 1670471100,
        "v": 124169
      },
      {
        "ts": 1671162300,
        "v": 123444
      },
      {
        "ts": 1671594300,
        "v": 120595
      },
      {
        "ts": 1671767100,
        "v": 118286
      },
      {
        "ts": 1674791100,
        "v": 118039
      },
      {
        "ts": 1681875900,
        "v": 116948
      },
      {
        "ts": 1682394300,
        "v": 118901
      },
      {
        "ts": 1683258300,
        "v": 117800
      },
      {
        "ts": 1683690300,
        "v": 119360
      },
      {
        "ts": 1684899900,
        "v": 117773
      },
      {
        "ts": 1685418300,
        "v": 115264
      },
      {
        "ts": 1686109500,
        "v": 117025
      },
      {
        "ts": 1688355900,
        "v": 118307
      },
      {
        "ts": 1690170300,
        "v": 120869
      },
      {
        "ts": 1690861500,
        "v": 130074
      },
      {
        "ts": 1691034300,
        "v": 130471
      },
      {
        "ts": 1691639100,
        "v": 128814
      },
      {
        "ts": 1691984700,
        "v": 127251
      },
      {
        "ts": 1693453500,
        "v": 135576
      },
      {
        "ts": 1694490300,
        "v": 136750
      },
      {
        "ts": 1695354300,
        "v": 138778
      },
      {
        "ts": 1696823100,
        "v": 136370
      },
      {
        "ts": 1697514300,
        "v": 141974
      },
      {
        "ts": 1698205500,
        "v": 141624
      },
      {
        "ts": 1699501500,
        "v": 141790
      },
      {
        "ts": 1700192700,
        "v": 140287
      },
      {
        "ts": 1701229500,
        "v": 140602
      },
      {
        "ts": 1702266300,
        "v": 149824
      },
      {
        "ts": 1703043900,
        "v": 148274
      },
      {
        "ts": 1704080700,
        "v": 153562
      },
      {
        "ts": 1704685500,
        "v": 152656
      },
      {
        "ts": 1705463100,
        "v": 152019
      },
      {
        "ts": 1707191100,
        "v": 154463
      },
      {
        "ts": 1707882300,
        "v": 154040
      },
      {
        "ts": 1709178300,
        "v": 158295
      },
      {
        "ts": 1710215100,
        "v": 156370
      },
      {
        "ts": 1711424700,
        "v": 170552
      },
      {
        "ts": 1712720700,
        "v": 179260
      },
      {
        "ts": 1713930300,
        "v": 181254
      },
      {
        "ts": 1715053500,
        "v": 193174
      },
      {
        "ts": 1716435900,
        "v": 195414
      },
      {
        "ts": 1717472700,
        "v": 201065
      },
      {
        "ts": 1717472700,
        "v": 195956
      },
      {
        "ts": 1718336700,
        "v": 200149
      },
      {
        "ts": 1719546300,
        "v": 201370
      },
      {
        "ts": 1720410300,
        "v": 202857
      },
      {
        "ts": 1721706300,
        "v": 210552
      },
      {
        "ts": 1722224700,
        "v": 206434
      },
      {
        "ts": 1722829500,
        "v": 209995
      },
      {
        "ts": 1723175100,
        "v": 203858
      },
      {
        "ts": 1724384700,
        "v": 208319
      },
      {
        "ts": 1725507900,
        "v": 213902
      },
      {
        "ts": 1726631100,
        "v": 219510
      },
      {
        "ts": 1727322300,
        "v": 221008
      },
      {
        "ts": 1728359100,
        "v": 229304
      },
      {
        "ts": 1731383100,
        "v": 233151
      },
      {
        "ts": 1733456700,
        "v": 233894
      },
      {
        "ts": 1734061500,
        "v": 232163
      },
      {
        "ts": 1736135100,
        "v": 231642
      },
      {
        "ts": 1743047100,
        "v": 229741
      },
      {
        "ts": 1744083900,
        "v": 227749
      },
      {
        "ts": 1745552700,
        "v": 228901
      },
      {
        "ts": 1746157500,
        "v": 227372
      },
      {
        "ts": 1747194300,
        "v": 226265
      },
      {
        "ts": 1747971900,
        "v": 224194
      },
      {
        "ts": 1748317500,
        "v": 226178
      },
      {
        "ts": 1749181500,
        "v": 226010
      },
      {
        "ts": 1751341500,
        "v": 233192
      },
      {
        "ts": 1752119100,
        "v": 233184
      },
      {
        "ts": 1752810300,
        "v": 229264
      },
      {
        "ts": 1753674300,
        "v": 232888
      },
      {
        "ts": 1756179900,
        "v": 239477
      },
      {
        "ts": 1758080700,
        "v": 274389
      },
      {
        "ts": 1760672700,
        "v": 271043
      },
      {
        "ts": 1762400700,
        "v": 275572
      },
      {
        "ts": 1763523900,
        "v": 271437
      },
      {
        "ts": 1764301500,
        "v": 274701
      },
      {
        "ts": 1765251900,
        "v": 272715
      },
      {
        "ts": 1767930300,
        "v": 270747
      },
      {
        "ts": 1768967100,
        "v": 274489
      },
      {
        "ts": 1771299900,
        "v": 277785
      },
      {
        "ts": 1773114300,
        "v": 284295
      },
      {
        "ts": 1774842300,
        "v": 282001
      }
    ]
  },
  "market": {
    "gear": 1,
    "gearLabel": "1st Gear",
    "verdict": "Environment nahi hai bhaiya. Smallcap index moving averages ke neeche hai — scan band, cash bhi ek position hai. Jab first signs of strength aayenge, hum ready honge. Wait for the right opportunity.",
    "checks": [
      {
        "label": "CNX Smallcap vs 50 DMA",
        "status": "bad",
        "note": "50 DMA ke neeche — environment kharab"
      },
      {
        "label": "10 DMA",
        "status": "bad",
        "note": "10 DMA ke neeche — scan ka time nahi"
      },
      {
        "label": "Breakouts working?",
        "status": "bad",
        "note": "Sirf 23% breakouts move kar rahe (49 traction, 81 flat, 81 fail) — pop & drop, choppy phase, chhoti size"
      },
      {
        "label": "Breadth (50 DMA ke upar)",
        "status": "warn",
        "note": "48% universe 50 DMA ke upar"
      },
      {
        "label": "Advance / Decline",
        "status": "warn",
        "note": "475 advances vs 817 declines aaj"
      },
      {
        "label": "52W high zone",
        "status": "bad",
        "note": "78 stocks 52W-high zone me, 121 low zone me"
      },
      {
        "label": "USDINR",
        "status": "good",
        "note": "USDINR -0.79% — rupaya stable/strong, positive"
      }
    ]
  },
  "hotSectors": [
    {
      "name": "Forest Materials",
      "note": "5 din me avg +4.79% · 2/4 stocks me lagatar action"
    }
  ],
  "sectorPlays": [
    {
      "name": "Forest Materials",
      "note": "5 din me avg +4.79% · 2/4 stocks me lagatar action",
      "depthNote": "20 din -0.89% · 60 din +5.99% · 1/4 naamon ne 20-din ka high toda · 2 52W-high zone me",
      "fire": "reaction",
      "stocks": [
        {
          "rank": 1,
          "leaderPct": 67,
          "symbol": "JKPAPER",
          "name": "JK Paper",
          "cap": "Micro",
          "cmp": 401.1,
          "pivot": 404.9,
          "sl": 386.7,
          "prox": 0.96,
          "range": 7.46,
          "baseDays": 25,
          "stage": "Pivot pe khada",
          "flags": [
            "Super tight",
            "Volume shrink",
            "52W high zone",
            "5% stock"
          ],
          "isPick": false
        },
        {
          "rank": 2,
          "leaderPct": 100,
          "symbol": "WSTCSTPAPR",
          "name": "West Coast Paper Mills",
          "cap": "Micro",
          "cmp": 653.6,
          "pivot": 658.5,
          "sl": 628.9,
          "prox": 0.75,
          "range": 12.93,
          "baseDays": 19,
          "stage": "Pivot pe khada",
          "flags": [
            "Tight base",
            "Volume shrink",
            "52W high zone",
            "5% stock"
          ],
          "isPick": false
        }
      ]
    }
  ],
  "universeHealth": {
    "listed": 2287,
    "prefiltered": 1333,
    "fetched": 1292,
    "scanned": 1140,
    "skippedShortHistory": 16,
    "skippedIlliquid": 136,
    "noSector": 2,
    "bseStitched": 18,
    "bseOnly": 0,
    "bseRejected": 0,
    "sectorCoveragePct": 97
  },
  "picks": [],
  "watchlist": [
    {
      "symbol": "JKPAPER",
      "name": "JK Paper",
      "sector": "Forest Materials",
      "cap": "Micro",
      "cmp": 401.1,
      "pivot": 404.9,
      "sl": 386.7,
      "prox": 0.96,
      "range": 7.46,
      "baseDays": 25,
      "ready": true,
      "leaderPct": 67,
      "flags": [
        "Hot sector",
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": true
    },
    {
      "symbol": "WSTCSTPAPR",
      "name": "West Coast Paper Mills",
      "sector": "Forest Materials",
      "cap": "Micro",
      "cmp": 653.6,
      "pivot": 658.5,
      "sl": 628.9,
      "prox": 0.75,
      "range": 12.93,
      "baseDays": 19,
      "ready": true,
      "leaderPct": 100,
      "flags": [
        "Hot sector",
        "Tight base",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": true
    },
    {
      "symbol": "VIJAYA",
      "name": "Vijaya Diagnostic Centre",
      "sector": "Healthcare",
      "cap": "Small",
      "cmp": 1499,
      "pivot": 1525,
      "sl": 1456,
      "prox": 1.73,
      "range": 5.67,
      "baseDays": 13,
      "ready": true,
      "leaderPct": 60,
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": false
    },
    {
      "symbol": "POLYPLEX",
      "name": "Polyplex Corporation",
      "sector": "Chemicals",
      "cap": "Micro",
      "cmp": 1188,
      "pivot": 1222,
      "sl": 1167,
      "prox": 2.89,
      "range": 6.31,
      "baseDays": 14,
      "ready": true,
      "leaderPct": 84,
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": false
    },
    {
      "symbol": "SUPRAJIT",
      "name": "Suprajit Engineering",
      "sector": "Automobile and Auto Components",
      "cap": "Micro",
      "cmp": 506.5,
      "pivot": 522.3,
      "sl": 498.8,
      "prox": 3.14,
      "range": 5.08,
      "baseDays": 9,
      "ready": true,
      "leaderPct": 44,
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": false
    },
    {
      "symbol": "DYNAMATECH",
      "name": "Dynamatic Technologies",
      "sector": "Capital Goods",
      "cap": "Micro",
      "cmp": 11678,
      "pivot": 12050,
      "sl": 11508,
      "prox": 3.19,
      "range": 5.97,
      "baseDays": 9,
      "ready": true,
      "leaderPct": 62,
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": false
    },
    {
      "symbol": "ETHOSLTD",
      "name": "Ethos",
      "sector": "Consumer Durables",
      "cap": "Micro",
      "cmp": 2879,
      "pivot": 2937,
      "sl": 2822,
      "prox": 1.99,
      "range": 3.99,
      "baseDays": 10,
      "ready": true,
      "leaderPct": 69,
      "flags": [
        "Super tight",
        "Volume shrink",
        "5% stock"
      ],
      "hot": false
    },
    {
      "symbol": "TASTYBITE",
      "name": "Tasty Bite Eatables",
      "sector": "Fast Moving Consumer Goods",
      "cap": "Micro",
      "cmp": 9946,
      "pivot": 10300,
      "sl": 9837,
      "prox": 3.56,
      "range": 5.48,
      "baseDays": 8,
      "ready": true,
      "leaderPct": 86,
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": false
    },
    {
      "symbol": "CUB",
      "name": "City Union Bank",
      "sector": "Financial Services",
      "cap": "Small",
      "cmp": 235,
      "pivot": 236,
      "sl": 225.4,
      "prox": 0.43,
      "range": 10.49,
      "baseDays": 11,
      "ready": true,
      "leaderPct": 87,
      "flags": [
        "Tight base",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": false
    },
    {
      "symbol": "HONASA",
      "name": "Honasa Consumer",
      "sector": "Fast Moving Consumer Goods",
      "cap": "Small",
      "cmp": 473.5,
      "pivot": 493.5,
      "sl": 471.3,
      "prox": 4.22,
      "range": 5.76,
      "baseDays": 11,
      "ready": true,
      "leaderPct": 75,
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "hot": false
    }
  ],
  "readyCount": 223,
  "candidateCount": 418,
  "lastPicks": {
    "date": "25 Aug",
    "picks": [
      {
        "picked": "25 Aug",
        "symbol": "VENKEYS",
        "sector": "Agri",
        "status": "no-cash",
        "pnlPct": 0,
        "reason": "Breakout to aaya, par capital pehle se lagi hui thi (₹4,67,015 deployed) — ye trade chhoot gayi. Cash bhi ek position hai."
      }
    ],
    "triggered": 0,
    "total": 1
  },
  "watchStats": {
    "windowDays": 15,
    "settled": 0,
    "settledCrossed": 0,
    "crossRate": null,
    "avgSessionsToCross": null,
    "tracking": [
      {
        "symbol": "VRLLOG",
        "sector": "Logistics / Shipping",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": true,
        "inSessions": 1,
        "maxHighPct": 0.23
      },
      {
        "symbol": "SYRMA",
        "sector": "Electronics / EMS",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      },
      {
        "symbol": "HOMEFIRST",
        "sector": "Financial Services",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      },
      {
        "symbol": "ARMANFIN",
        "sector": "NBFC / Finance",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      },
      {
        "symbol": "SHREEJISPG",
        "sector": "Logistics / Shipping",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      },
      {
        "symbol": "SEAMECLTD",
        "sector": "Logistics / Shipping",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      },
      {
        "symbol": "KRN",
        "sector": "Capital Goods",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": true,
        "inSessions": 1,
        "maxHighPct": 3.47
      },
      {
        "symbol": "CNL",
        "sector": "Electronics / EMS",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": true,
        "inSessions": 1,
        "maxHighPct": 4.16
      },
      {
        "symbol": "ANANDRATHI",
        "sector": "Financial Services",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      },
      {
        "symbol": "MARKSANS",
        "sector": "Healthcare",
        "from": "28 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      },
      {
        "symbol": "AGARWALEYE",
        "sector": "Healthcare",
        "from": "31 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      },
      {
        "symbol": "HONASA",
        "sector": "Fast Moving Consumer Goods",
        "from": "31 Aug",
        "sessions": 2,
        "crossed": false,
        "inSessions": null,
        "maxHighPct": 0
      }
    ],
    "trackingCount": 26
  },
  "positions": [
    {
      "symbol": "ANANDRATHI",
      "sector": "Financial Services",
      "gear": 5,
      "sizePct": 24,
      "picked": "18 Jun",
      "pickedTs": 1781754300,
      "triggerDate": "19 Jun",
      "daysHeld": 51,
      "entry": 1857,
      "qty": 38,
      "invested": 70566,
      "cmp": 2197,
      "pnlPct": 18.31,
      "pnlAmt": 12920.63,
      "sl": 1773,
      "slDistPct": 19.3,
      "booked": true,
      "bookAt": 2043,
      "trail": 2118,
      "next": "Aadha book ho chuka. Ab 40 DMA (₹2118) ke neeche CLOSE = bahar",
      "stale": false,
      "spark": [
        2132,
        2158,
        2189,
        2199,
        2175,
        2176,
        2195,
        2189,
        2171,
        2188,
        2168,
        2164,
        2179,
        2183,
        2213,
        2204,
        2197
      ]
    },
    {
      "symbol": "WELCORP",
      "sector": "Capital Goods",
      "gear": 2,
      "sizePct": 24,
      "picked": "23 Jun",
      "pickedTs": 1782186300,
      "triggerDate": "25 Jun",
      "daysHeld": 47,
      "entry": 1439,
      "qty": 50,
      "invested": 71950,
      "cmp": 2554,
      "pnlPct": 77.48,
      "pnlAmt": 55746.86,
      "sl": 1374,
      "slDistPct": 46.2,
      "booked": true,
      "bookAt": 1583,
      "trail": 1860,
      "next": "Aadha book ho chuka. Ab 40 DMA (₹1860) ke neeche CLOSE = bahar",
      "stale": false,
      "spark": [
        1849,
        1837,
        1868,
        1884,
        1873,
        1882,
        1917,
        1974,
        2005,
        2312,
        2409,
        2346,
        2307,
        2406,
        2374,
        2391,
        2554
      ]
    },
    {
      "symbol": "AKUMS",
      "sector": "Healthcare",
      "gear": 4,
      "sizePct": 24,
      "picked": "2 Jul",
      "pickedTs": 1782963900,
      "triggerDate": "3 Jul",
      "daysHeld": 42,
      "entry": 642.9,
      "qty": 112,
      "invested": 72004.8,
      "cmp": 779.1,
      "pnlPct": 21.19,
      "pnlAmt": 15257.82,
      "sl": 614,
      "slDistPct": 21.19,
      "booked": true,
      "bookAt": 707.2,
      "trail": 710,
      "next": "Aadha book ho chuka. Ab 40 DMA (₹710) ke neeche CLOSE = bahar",
      "stale": false,
      "spark": [
        730.1,
        761,
        750,
        751.8,
        726.6,
        744,
        744.2,
        753.3,
        752.9,
        750,
        770.3,
        745,
        766.1,
        761.2,
        772.6,
        776.7,
        779.1
      ]
    },
    {
      "symbol": "BALRAMCHIN",
      "sector": "Agri",
      "gear": 3,
      "sizePct": 24,
      "picked": "17 Aug",
      "pickedTs": 1786938300,
      "triggerDate": "18 Aug",
      "daysHeld": 10,
      "entry": 665.5,
      "qty": 109,
      "invested": 72539.5,
      "cmp": 668.9,
      "pnlPct": 0.51,
      "pnlAmt": 369.95,
      "sl": 635.6,
      "slDistPct": 4.98,
      "booked": true,
      "bookAt": 732.1,
      "trail": 630.9,
      "next": "Aadha book ho chuka. Ab 40 DMA (₹630.9) ke neeche CLOSE = bahar",
      "stale": false,
      "spark": [
        655.3,
        627.8,
        604.7,
        619.7,
        624.8,
        655.8,
        653.3,
        650.8,
        767.1,
        729.3,
        695.5,
        668.1,
        674.3,
        650,
        654.8,
        693.5,
        668.9
      ]
    },
    {
      "symbol": "NAVINFLUOR",
      "sector": "Chemicals",
      "gear": 2,
      "sizePct": 24,
      "picked": "24 Aug",
      "pickedTs": 1787543100,
      "triggerDate": "26 Aug",
      "daysHeld": 4,
      "entry": 8451,
      "qty": 17,
      "invested": 143667,
      "cmp": 8636,
      "pnlPct": 2.19,
      "pnlAmt": 3146.31,
      "sl": 8110,
      "slDistPct": 6.09,
      "booked": false,
      "bookAt": 9296,
      "trail": 7969,
      "next": "+10% pe (₹9296) aadha book hoga — abhi 7.64% door",
      "stale": false,
      "spark": [
        8197,
        8156,
        8357,
        8294,
        8235,
        8151,
        8255,
        8278,
        8256,
        8207,
        8187,
        8209,
        8553,
        8568,
        8518,
        8676,
        8636
      ]
    }
  ],
  "deployed": 430727.3,
  "journal": [
    {
      "picked": "8 Apr",
      "symbol": "VTL",
      "sector": "Textiles",
      "cap": "Small",
      "gear": 2,
      "entry": 559.9,
      "qty": 128,
      "invested": 71667.2,
      "status": "sl",
      "pnlPct": -4.5,
      "exitDate": "13 Apr",
      "reason": "SL hit 534.7 pe — out, end of story. Sell is a sell.",
      "ts": 1775619900,
      "exitTs": 1776051900,
      "bt": true
    },
    {
      "picked": "10 Apr",
      "symbol": "GMDCLTD",
      "sector": "Metals & Mining",
      "cap": "Small",
      "gear": 3,
      "entry": 614.4,
      "qty": 58,
      "invested": 35635.2,
      "status": "win",
      "pnlPct": 21.54,
      "exitDate": "16 Apr",
      "reason": "+21.54% — double digit aa gaya, 50% book kiya. Baaki 40 DMA pe trail hoga.",
      "ts": 1775792700,
      "exitTs": 1776311100,
      "bt": true
    },
    {
      "picked": "15 Apr",
      "symbol": "CEIGALL",
      "sector": "Construction",
      "cap": "Micro",
      "gear": 3,
      "entry": 304.5,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776224700,
      "exitTs": 1776397500,
      "bt": true
    },
    {
      "picked": "16 Apr",
      "symbol": "ASTERDM",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 3,
      "entry": 689.6,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776311100,
      "exitTs": 1776397500,
      "bt": true
    },
    {
      "picked": "16 Apr",
      "symbol": "SAIL",
      "sector": "Metals & Mining",
      "cap": "Mid",
      "gear": 3,
      "entry": 172.1,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776311100,
      "exitTs": 1776397500,
      "bt": true
    },
    {
      "picked": "8 Apr",
      "symbol": "STYLAMIND",
      "sector": "Consumer Durables",
      "cap": "Micro",
      "gear": 2,
      "entry": 2245,
      "qty": 31,
      "invested": 69595,
      "status": "fail",
      "pnlPct": -0.22,
      "exitDate": "20 Apr",
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1775619900,
      "exitTs": 1776656700,
      "bt": true
    },
    {
      "picked": "13 Apr",
      "symbol": "TRAVELFOOD",
      "sector": "Consumer Services",
      "cap": "Small",
      "gear": 2,
      "entry": 1325,
      "qty": 54,
      "invested": 71550,
      "status": "fail",
      "pnlPct": -2.25,
      "exitDate": "20 Apr",
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1776051900,
      "exitTs": 1776656700,
      "bt": true
    },
    {
      "picked": "15 Apr",
      "symbol": "VTL",
      "sector": "Textiles",
      "cap": "Small",
      "gear": 3,
      "entry": 566,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776224700,
      "exitTs": 1776656700,
      "bt": true
    },
    {
      "picked": "17 Apr",
      "symbol": "GRANULES",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 3,
      "entry": 660.5,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776397500,
      "exitTs": 1776656700,
      "bt": true
    },
    {
      "picked": "17 Apr",
      "symbol": "SAIL",
      "sector": "Metals & Mining",
      "cap": "Mid",
      "gear": 3,
      "entry": 175,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776397500,
      "exitTs": 1776743100,
      "bt": true
    },
    {
      "picked": "20 Apr",
      "symbol": "APLAPOLLO",
      "sector": "Metals & Mining",
      "cap": "Mid",
      "gear": 3,
      "entry": 2151,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776656700,
      "exitTs": 1776743100,
      "bt": true
    },
    {
      "picked": "21 Apr",
      "symbol": "CCL",
      "sector": "Fast Moving Consumer Goods",
      "cap": "Small",
      "gear": 4,
      "entry": 1130,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776743100,
      "exitTs": 1776829500,
      "bt": true
    },
    {
      "picked": "22 Apr",
      "symbol": "ASHIANA",
      "sector": "Realty",
      "cap": "Micro",
      "gear": 4,
      "entry": 343.7,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776829500,
      "exitTs": 1776915900,
      "bt": true
    },
    {
      "picked": "20 Apr",
      "symbol": "STYLAMIND",
      "sector": "Consumer Durables",
      "cap": "Micro",
      "gear": 3,
      "entry": 2268,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1776656700,
      "exitTs": 1777002300,
      "bt": true
    },
    {
      "picked": "21 Apr",
      "symbol": "TVSHLTD",
      "sector": "Automobile and Auto Components",
      "cap": "Micro",
      "gear": 4,
      "entry": 14887,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1776743100,
      "exitTs": 1777261500,
      "bt": true
    },
    {
      "picked": "22 Apr",
      "symbol": "BANDHANBNK",
      "sector": "Financial Services",
      "cap": "Small",
      "gear": 4,
      "entry": 178.3,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1776829500,
      "exitTs": 1777261500,
      "bt": true
    },
    {
      "picked": "10 Apr",
      "symbol": "NATIONALUM",
      "sector": "Metals & Mining",
      "cap": "Mid",
      "gear": 3,
      "entry": 418.5,
      "qty": 171,
      "invested": 71563.5,
      "status": "sl",
      "pnlPct": -4.49,
      "exitDate": "30 Apr",
      "reason": "SL hit 399.7 pe — out, end of story. Sell is a sell.",
      "ts": 1775792700,
      "exitTs": 1777520700,
      "bt": true
    },
    {
      "picked": "4 May",
      "symbol": "STYLAMIND",
      "sector": "Consumer Durables",
      "cap": "Micro",
      "gear": 3,
      "entry": 2268,
      "qty": 15,
      "invested": 34020,
      "status": "win",
      "pnlPct": 16.17,
      "exitDate": "7 May",
      "reason": "+16.17% — double digit aa gaya, 50% book kiya. Baaki 40 DMA pe trail hoga.",
      "ts": 1777866300,
      "exitTs": 1778125500,
      "bt": true
    },
    {
      "picked": "6 May",
      "symbol": "PRUDENT",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 4,
      "entry": 2944,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1778039100,
      "exitTs": 1778125500,
      "bt": true
    },
    {
      "picked": "7 May",
      "symbol": "NATCOPHARM",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 4,
      "entry": 1174,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1778125500,
      "exitTs": 1778211900,
      "bt": true
    },
    {
      "picked": "4 May",
      "symbol": "THANGAMAYL",
      "sector": "Consumer Durables",
      "cap": "Micro",
      "gear": 3,
      "entry": 4040,
      "qty": 17,
      "invested": 68680,
      "status": "sl",
      "pnlPct": -4.5,
      "exitDate": "11 May",
      "reason": "SL hit 3858 pe — out, end of story. Sell is a sell.",
      "ts": 1777866300,
      "exitTs": 1778471100,
      "bt": true
    },
    {
      "picked": "6 May",
      "symbol": "PNBHOUSING",
      "sector": "Financial Services",
      "cap": "Small",
      "gear": 4,
      "entry": 1071,
      "qty": 135,
      "invested": 144585,
      "status": "fail",
      "pnlPct": -0.76,
      "exitDate": "13 May",
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1778039100,
      "exitTs": 1778643900,
      "bt": true
    },
    {
      "picked": "7 May",
      "symbol": "SAILIFE",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 4,
      "entry": 1100,
      "qty": 131,
      "invested": 144100,
      "status": "fail",
      "pnlPct": -1.33,
      "exitDate": "13 May",
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1778125500,
      "exitTs": 1778643900,
      "bt": true
    },
    {
      "picked": "8 May",
      "symbol": "VENKEYS",
      "sector": "Agri",
      "cap": "Micro",
      "gear": 3,
      "entry": 1641,
      "qty": 88,
      "invested": 144408,
      "status": "sl",
      "pnlPct": -4.51,
      "exitDate": "14 May",
      "reason": "SL hit 1567 pe — out, end of story. Sell is a sell.",
      "ts": 1778211900,
      "exitTs": 1778730300,
      "bt": true
    },
    {
      "picked": "8 May",
      "symbol": "ITI",
      "sector": "Telecommunication",
      "cap": "Small",
      "gear": 3,
      "entry": 312.3,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1778211900,
      "exitTs": 1778730300,
      "bt": true
    },
    {
      "picked": "10 Apr",
      "symbol": "GMDCLTD",
      "sector": "Metals & Mining",
      "cap": "Small",
      "gear": 3,
      "entry": 614.4,
      "qty": 58,
      "invested": 35635.2,
      "status": "win",
      "pnlPct": 2.99,
      "exitDate": "18 May",
      "reason": "40 DMA trail exit — jo mila le liya",
      "ts": 1775792700,
      "exitTs": 1779075900,
      "bt": true
    },
    {
      "picked": "25 May",
      "symbol": "MBAPL",
      "sector": "Agri",
      "cap": "Micro",
      "gear": 4,
      "entry": 110.8,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1779680700,
      "exitTs": 1779767100,
      "bt": true
    },
    {
      "picked": "25 May",
      "symbol": "OPTIEMUS",
      "sector": "Telecommunication",
      "cap": "Micro",
      "gear": 4,
      "entry": 434.9,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1779680700,
      "exitTs": 1779767100,
      "bt": true
    },
    {
      "picked": "26 May",
      "symbol": "SONACOMS",
      "sector": "Automobile and Auto Components",
      "cap": "Small",
      "gear": 3,
      "entry": 614,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1779767100,
      "exitTs": 1779853500,
      "bt": true
    },
    {
      "picked": "26 May",
      "symbol": "SJS",
      "sector": "Automobile and Auto Components",
      "cap": "Micro",
      "gear": 3,
      "entry": 2050,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1779767100,
      "exitTs": 1779853500,
      "bt": true
    },
    {
      "picked": "13 Apr",
      "symbol": "NMDC",
      "sector": "Metals & Mining",
      "cap": "Mid",
      "gear": 2,
      "entry": 87,
      "qty": 823,
      "invested": 71601,
      "status": "win",
      "pnlPct": 1.14,
      "exitDate": "29 May",
      "reason": "40 DMA trail exit — jo mila le liya",
      "ts": 1776051900,
      "exitTs": 1780026300,
      "bt": true
    },
    {
      "picked": "22 May",
      "symbol": "EMCURE",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 2,
      "entry": 1758,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1779421500,
      "exitTs": 1780026300,
      "bt": true
    },
    {
      "picked": "22 May",
      "symbol": "RAINBOW",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 2,
      "entry": 1365,
      "qty": 52,
      "invested": 70980,
      "status": "fail",
      "pnlPct": -1.73,
      "exitDate": "2 Jun",
      "reason": "Breakout fail — 5 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1779421500,
      "exitTs": 1780371900,
      "bt": true
    },
    {
      "picked": "27 May",
      "symbol": "SONACOMS",
      "sector": "Automobile and Auto Components",
      "cap": "Small",
      "gear": 4,
      "entry": 621.8,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1779853500,
      "exitTs": 1780458300,
      "bt": true
    },
    {
      "picked": "27 May",
      "symbol": "FIEMIND",
      "sector": "Automobile and Auto Components",
      "cap": "Micro",
      "gear": 4,
      "entry": 2325,
      "qty": 30,
      "invested": 69750,
      "status": "fail",
      "pnlPct": -2.03,
      "exitDate": "8 Jun",
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1779853500,
      "exitTs": 1780890300,
      "bt": true
    },
    {
      "picked": "12 Jun",
      "symbol": "PIRAMALFIN",
      "sector": "Financial Services",
      "cap": "Small",
      "gear": 2,
      "entry": 2045,
      "qty": 34,
      "invested": 69530,
      "status": "fail",
      "pnlPct": -2.28,
      "exitDate": "18 Jun",
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1781235900,
      "exitTs": 1781754300,
      "bt": true
    },
    {
      "picked": "15 Jun",
      "symbol": "ANANDRATHI",
      "sector": "Financial Services",
      "cap": "Small",
      "gear": 3,
      "entry": 1850,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1781495100,
      "exitTs": 1781754300,
      "bt": true
    },
    {
      "picked": "17 Jun",
      "symbol": "NAM-INDIA",
      "sector": "Financial Services",
      "cap": "Mid",
      "gear": 4,
      "entry": 1159,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Test mode — abhi sirf 1 position profit me hai. Pehle 2 chalein, tab gear up. Tab tak nayi position nahi.",
      "ts": 1781667900,
      "exitTs": 1781754300,
      "bt": true
    },
    {
      "picked": "12 Jun",
      "symbol": "SBC",
      "sector": "Diversified",
      "cap": "Micro",
      "gear": 2,
      "entry": 37.9,
      "qty": 936,
      "invested": 35474.4,
      "status": "win",
      "pnlPct": 15.01,
      "exitDate": "19 Jun",
      "reason": "+15.01% — double digit aa gaya, 50% book kiya. Baaki 40 DMA pe trail hoga.",
      "ts": 1781235900,
      "exitTs": 1781840700,
      "bt": true
    },
    {
      "picked": "15 Jun",
      "symbol": "IIFLCAPS",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 3,
      "entry": 351,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1781495100,
      "exitTs": 1781840700,
      "bt": true
    },
    {
      "picked": "16 Jun",
      "symbol": "KTKBANK",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 3,
      "entry": 283,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1781581500,
      "exitTs": 1782099900,
      "bt": true
    },
    {
      "picked": "19 Jun",
      "symbol": "MAHSCOOTER",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 5,
      "entry": 12840,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1781840700,
      "exitTs": 1782099900,
      "bt": true
    },
    {
      "picked": "19 Jun",
      "symbol": "ZYDUSWELL",
      "sector": "Fast Moving Consumer Goods",
      "cap": "Small",
      "gear": 5,
      "entry": 516.2,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1781840700,
      "exitTs": 1782099900,
      "bt": true
    },
    {
      "picked": "22 Jun",
      "symbol": "HONAUT",
      "sector": "Capital Goods",
      "cap": "Mid",
      "gear": 5,
      "entry": 38450,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1782099900,
      "exitTs": 1782186300,
      "bt": true
    },
    {
      "picked": "22 Jun",
      "symbol": "WELCORP",
      "sector": "Capital Goods",
      "cap": "Small",
      "gear": 5,
      "entry": 1434,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1782099900,
      "exitTs": 1782186300,
      "bt": true
    },
    {
      "picked": "18 Jun",
      "symbol": "JSFB",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 5,
      "entry": 488.9,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1781754300,
      "exitTs": 1782272700,
      "bt": true
    },
    {
      "picked": "17 Jun",
      "symbol": "CANFINHOME",
      "sector": "Financial Services",
      "cap": "Small",
      "gear": 4,
      "entry": 894.8,
      "qty": 159,
      "invested": 142273.2,
      "status": "fail",
      "pnlPct": -0.96,
      "exitDate": "25 Jun",
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1781667900,
      "exitTs": 1782359100,
      "bt": true
    },
    {
      "picked": "24 Jun",
      "symbol": "GUFICBIO",
      "sector": "Healthcare",
      "cap": "Micro",
      "gear": 3,
      "entry": 377.5,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1782272700,
      "exitTs": 1782704700,
      "bt": true
    },
    {
      "picked": "24 Jun",
      "symbol": "ALKEM",
      "sector": "Healthcare",
      "cap": "Mid",
      "gear": 3,
      "entry": 5511,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1782272700,
      "exitTs": 1782704700,
      "bt": true
    },
    {
      "picked": "23 Jun",
      "symbol": "SGMART",
      "sector": "Capital Goods",
      "cap": "Micro",
      "gear": 2,
      "entry": 618,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1782186300,
      "exitTs": 1782791100,
      "bt": true
    },
    {
      "picked": "30 Jun",
      "symbol": "PGHL",
      "sector": "Healthcare",
      "cap": "Micro",
      "gear": 3,
      "entry": 6399,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1782791100,
      "exitTs": 1782877500,
      "bt": true
    },
    {
      "picked": "1 Jul",
      "symbol": "KIMS",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 3,
      "entry": 841,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1782877500,
      "exitTs": 1782963900,
      "bt": true
    },
    {
      "picked": "18 Jun",
      "symbol": "ANANDRATHI",
      "sector": "Financial Services",
      "cap": "Small",
      "gear": 5,
      "entry": 1857,
      "qty": 38,
      "invested": 70566,
      "status": "win",
      "pnlPct": 11.02,
      "exitDate": "3 Jul",
      "reason": "+11.02% — double digit aa gaya, 50% book kiya. Baaki 40 DMA pe trail hoga.",
      "ts": 1781754300,
      "exitTs": 1783050300,
      "bt": true
    },
    {
      "picked": "30 Jun",
      "symbol": "LALPATHLAB",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 3,
      "entry": 1699,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1782791100,
      "exitTs": 1783309500,
      "bt": true
    },
    {
      "picked": "1 Jul",
      "symbol": "IIFLCAPS",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 3,
      "entry": 349.8,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1782877500,
      "exitTs": 1783395900,
      "bt": true
    },
    {
      "picked": "6 Jul",
      "symbol": "LALPATHLAB",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 3,
      "entry": 1699,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1783309500,
      "exitTs": 1783395900,
      "bt": true
    },
    {
      "picked": "2 Jul",
      "symbol": "STAR",
      "sector": "Healthcare",
      "cap": "Micro",
      "gear": 4,
      "entry": 1150,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1782963900,
      "exitTs": 1783482300,
      "bt": true
    },
    {
      "picked": "23 Jun",
      "symbol": "WELCORP",
      "sector": "Capital Goods",
      "cap": "Small",
      "gear": 2,
      "entry": 1439,
      "qty": 49,
      "invested": 70511,
      "status": "win",
      "pnlPct": 11.32,
      "exitDate": "9 Jul",
      "reason": "+11.32% — double digit aa gaya, 50% book kiya. Baaki 40 DMA pe trail hoga.",
      "ts": 1782186300,
      "exitTs": 1783568700,
      "bt": true
    },
    {
      "picked": "3 Jul",
      "symbol": "PRUDENT",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 3,
      "entry": 3068,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1783050300,
      "exitTs": 1783568700,
      "bt": true
    },
    {
      "picked": "3 Jul",
      "symbol": "MIDHANI",
      "sector": "Defence",
      "cap": "Micro",
      "gear": 3,
      "entry": 443,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1783050300,
      "exitTs": 1783568700,
      "bt": true
    },
    {
      "picked": "6 Jul",
      "symbol": "DATAPATTNS",
      "sector": "Defence",
      "cap": "Small",
      "gear": 3,
      "entry": 4712,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1783309500,
      "exitTs": 1783655100,
      "bt": true
    },
    {
      "picked": "7 Jul",
      "symbol": "LALPATHLAB",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 2,
      "entry": 1718,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1783395900,
      "exitTs": 1783914300,
      "bt": true
    },
    {
      "picked": "7 Jul",
      "symbol": "ARVSMART",
      "sector": "Realty",
      "cap": "Micro",
      "gear": 2,
      "entry": 628.8,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1783395900,
      "exitTs": 1783914300,
      "bt": true
    },
    {
      "picked": "10 Jul",
      "symbol": "NYKAA",
      "sector": "New Age / Internet",
      "cap": "Mid",
      "gear": 4,
      "entry": 331,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1783655100,
      "exitTs": 1783914300,
      "bt": true
    },
    {
      "picked": "13 Jul",
      "symbol": "LALPATHLAB",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 4,
      "entry": 1738,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1783914300,
      "exitTs": 1784000700,
      "bt": true
    },
    {
      "picked": "10 Jul",
      "symbol": "SYRMA",
      "sector": "Electronics / EMS",
      "cap": "Small",
      "gear": 4,
      "entry": 1457,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1783655100,
      "exitTs": 1784173500,
      "bt": true
    },
    {
      "picked": "15 Jul",
      "symbol": "NIVABUPA",
      "sector": "Financial Services",
      "cap": "Small",
      "gear": 3,
      "entry": 89.5,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1784087100,
      "exitTs": 1784173500,
      "bt": true
    },
    {
      "picked": "13 Jul",
      "symbol": "IKS",
      "sector": "Information Technology",
      "cap": "Small",
      "gear": 4,
      "entry": 1933,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1783914300,
      "exitTs": 1784259900,
      "bt": true
    },
    {
      "picked": "15 Jul",
      "symbol": "RELIGARE",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 3,
      "entry": 278.8,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1784087100,
      "exitTs": 1784605500,
      "bt": true
    },
    {
      "picked": "16 Jul",
      "symbol": "SYRMA",
      "sector": "Electronics / EMS",
      "cap": "Small",
      "gear": 2,
      "entry": 1457,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1784173500,
      "exitTs": 1784691900,
      "bt": true
    },
    {
      "picked": "16 Jul",
      "symbol": "PRIVISCL",
      "sector": "Chemicals",
      "cap": "Micro",
      "gear": 2,
      "entry": 3760,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1784173500,
      "exitTs": 1784691900,
      "bt": true
    },
    {
      "picked": "21 Jul",
      "symbol": "KTKBANK",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 3,
      "entry": 283,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1784605500,
      "exitTs": 1784691900,
      "bt": true
    },
    {
      "picked": "21 Jul",
      "symbol": "DHANBANK",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 3,
      "entry": 35.4,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1784605500,
      "exitTs": 1784691900,
      "bt": true
    },
    {
      "picked": "20 Jul",
      "symbol": "SAILIFE",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 3,
      "entry": 1300,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1784519100,
      "exitTs": 1784864700,
      "bt": true
    },
    {
      "picked": "20 Jul",
      "symbol": "IKS",
      "sector": "Information Technology",
      "cap": "Small",
      "gear": 3,
      "entry": 1933,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1784519100,
      "exitTs": 1784864700,
      "bt": true
    },
    {
      "picked": "23 Jul",
      "symbol": "KTKBANK",
      "sector": "Financial Services",
      "cap": "Micro",
      "gear": 2,
      "entry": 284.9,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1784778300,
      "exitTs": 1785123900,
      "bt": true
    },
    {
      "picked": "22 Jul",
      "symbol": "EPL",
      "sector": "Capital Goods",
      "cap": "Micro",
      "gear": 2,
      "entry": 243,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1784691900,
      "exitTs": 1785210300,
      "bt": true
    },
    {
      "picked": "22 Jul",
      "symbol": "AETHER",
      "sector": "Chemicals",
      "cap": "Micro",
      "gear": 2,
      "entry": 1508,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1784691900,
      "exitTs": 1785210300,
      "bt": true
    },
    {
      "picked": "23 Jul",
      "symbol": "SUPRAJIT",
      "sector": "Automobile and Auto Components",
      "cap": "Micro",
      "gear": 2,
      "entry": 502,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1784778300,
      "exitTs": 1785296700,
      "bt": true
    },
    {
      "picked": "27 Jul",
      "symbol": "SFL",
      "sector": "Consumer Durables",
      "cap": "Micro",
      "gear": 3,
      "entry": 780,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785123900,
      "exitTs": 1785296700,
      "bt": true
    },
    {
      "picked": "29 Jul",
      "symbol": "RBLBANK",
      "sector": "Private Banks",
      "cap": "Small",
      "gear": 3,
      "entry": 382.4,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785296700,
      "exitTs": 1785383100,
      "bt": true
    },
    {
      "picked": "27 Jul",
      "symbol": "NIVABUPA",
      "sector": "Financial Services",
      "cap": "Small",
      "gear": 3,
      "entry": 89.7,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785123900,
      "exitTs": 1785469500,
      "bt": true
    },
    {
      "picked": "30 Jul",
      "symbol": "MINDACORP",
      "sector": "Automobile and Auto Components",
      "cap": "Small",
      "gear": 3,
      "entry": 713.7,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785383100,
      "exitTs": 1785469500,
      "bt": true
    },
    {
      "picked": "16 Jun",
      "symbol": "ABCAPITAL",
      "sector": "Financial Services",
      "cap": "Mid",
      "gear": 3,
      "entry": 376,
      "qty": 190,
      "invested": 71440,
      "status": "win",
      "pnlPct": 12.86,
      "exitDate": "3 Aug",
      "reason": "+12.86% — double digit aa gaya, 50% book kiya. Baaki 40 DMA pe trail hoga.",
      "ts": 1781581500,
      "exitTs": 1785728700,
      "bt": true
    },
    {
      "picked": "12 Jun",
      "symbol": "SBC",
      "sector": "Diversified",
      "cap": "Micro",
      "gear": 2,
      "entry": 37.9,
      "qty": 937,
      "invested": 35512.3,
      "status": "win",
      "pnlPct": 8.97,
      "exitDate": "5 Aug",
      "reason": "40 DMA trail exit — jo mila le liya",
      "ts": 1781235900,
      "exitTs": 1785901500,
      "bt": true
    },
    {
      "picked": "30 Jul",
      "symbol": "FIEMIND",
      "sector": "Automobile and Auto Components",
      "cap": "Micro",
      "gear": 3,
      "entry": 2424,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785383100,
      "exitTs": 1785901500,
      "bt": true
    },
    {
      "picked": "3 Aug",
      "symbol": "CASTROLIND",
      "sector": "Oil Gas & Consumable Fuels",
      "cap": "Small",
      "gear": 5,
      "entry": 189,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785728700,
      "exitTs": 1785901500,
      "bt": true
    },
    {
      "picked": "4 Aug",
      "symbol": "RISHABH",
      "sector": "Electronics / EMS",
      "cap": "Micro",
      "gear": 4,
      "entry": 663,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785815100,
      "exitTs": 1785901500,
      "bt": true
    },
    {
      "picked": "4 Aug",
      "symbol": "JAMNAAUTO",
      "sector": "Automobile and Auto Components",
      "cap": "Micro",
      "gear": 4,
      "entry": 143.5,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785815100,
      "exitTs": 1785901500,
      "bt": true
    },
    {
      "picked": "31 Jul",
      "symbol": "BHARATFORG",
      "sector": "Automobile and Auto Components",
      "cap": "Mid",
      "gear": 3,
      "entry": 2238,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1785469500,
      "exitTs": 1785987900,
      "bt": true
    },
    {
      "picked": "31 Jul",
      "symbol": "DELHIVERY",
      "sector": "New Age / Internet",
      "cap": "Small",
      "gear": 3,
      "entry": 493.4,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1785469500,
      "exitTs": 1785987900,
      "bt": true
    },
    {
      "picked": "5 Aug",
      "symbol": "LMW",
      "sector": "Capital Goods",
      "cap": "Micro",
      "gear": 4,
      "entry": 16500,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785901500,
      "exitTs": 1785987900,
      "bt": true
    },
    {
      "picked": "5 Aug",
      "symbol": "OLECTRA",
      "sector": "Automobile and Auto Components",
      "cap": "Small",
      "gear": 4,
      "entry": 1418,
      "status": "no-cash",
      "pnlPct": 0,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi — ye trade chhoot gayi",
      "ts": 1785901500,
      "exitTs": 1785987900,
      "bt": true
    },
    {
      "picked": "29 Jul",
      "symbol": "VIJAYA",
      "sector": "Healthcare",
      "cap": "Small",
      "gear": 3,
      "entry": 1379,
      "qty": 107,
      "invested": 147553,
      "status": "fail",
      "pnlPct": -2.02,
      "exitDate": "7 Aug",
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "ts": 1785296700,
      "exitTs": 1786074300,
      "bt": true
    },
    {
      "picked": "3 Aug",
      "symbol": "TVSHLTD",
      "sector": "Automobile and Auto Components",
      "cap": "Micro",
      "gear": 5,
      "entry": 15231,
      "status": "no-trigger",
      "pnlPct": 0,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "ts": 1785728700,
      "exitTs": 1786074300,
      "bt": true
    },
    {
      "picked": "2 Jul",
      "ts": 1782963900,
      "symbol": "AKUMS",
      "sector": "Healthcare",
      "gear": 4,
      "entry": 642.9,
      "qty": 112,
      "invested": 72004.8,
      "status": "win",
      "pnlPct": 13.56,
      "exitDate": "10 Aug",
      "exitTs": 1786336200,
      "reason": "+13.56% — double digit aa gaya, 50% book kiya. Baaki 40 DMA pe trail hoga.",
      "live": true
    },
    {
      "picked": "7 Aug",
      "ts": 1786074300,
      "symbol": "LLOYDSENT",
      "sector": "Metals & Mining",
      "gear": 4,
      "entry": 84.2,
      "status": "no-cash",
      "pnlPct": 0,
      "exitTs": 1786336200,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi (₹6,23,367 deployed) — ye trade chhoot gayi. Cash bhi ek position hai.",
      "live": true
    },
    {
      "picked": "6 Aug",
      "ts": 1785987900,
      "symbol": "SHREEJISPG",
      "sector": "Logistics / Shipping",
      "gear": 4,
      "entry": 677.2,
      "qty": 222,
      "invested": 150338.4,
      "status": "sl",
      "pnlPct": -4.5,
      "exitDate": "11 Aug",
      "exitTs": 1786419900,
      "reason": "SL hit 646.7 pe — out, end of story. Sell is a sell.",
      "live": true
    },
    {
      "picked": "6 Aug",
      "ts": 1785987900,
      "symbol": "SHYAMMETL",
      "sector": "Capital Goods",
      "gear": 4,
      "entry": 1045,
      "status": "no-trigger",
      "pnlPct": 0,
      "exitTs": 1786506300,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "live": true
    },
    {
      "picked": "16 Jun",
      "ts": 1781581500,
      "symbol": "ABCAPITAL",
      "sector": "Financial Services",
      "gear": 3,
      "entry": 376,
      "qty": 190,
      "invested": 71440,
      "status": "win",
      "pnlPct": 6.65,
      "exitDate": "14 Aug",
      "exitTs": 1786679100,
      "reason": "40 DMA trail exit — jo mila le liya",
      "live": true
    },
    {
      "picked": "7 Aug",
      "ts": 1786074300,
      "symbol": "CYIENTDLM",
      "sector": "Defence",
      "gear": 4,
      "entry": 701.3,
      "qty": 215,
      "invested": 150779.5,
      "status": "fail",
      "pnlPct": -0.66,
      "exitDate": "14 Aug",
      "exitTs": 1786679100,
      "reason": "Breakout fail — 4 din squat, move nahi aaya. Abnormal behavior = out.",
      "live": true
    },
    {
      "picked": "10 Aug",
      "ts": 1786336200,
      "symbol": "VMART",
      "sector": "Consumer Services",
      "gear": 4,
      "entry": 823.3,
      "status": "no-trigger",
      "pnlPct": 0,
      "exitTs": 1786679100,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "live": true
    },
    {
      "picked": "11 Aug",
      "ts": 1786419900,
      "symbol": "LALPATHLAB",
      "sector": "Healthcare",
      "gear": 3,
      "entry": 1974,
      "qty": 75,
      "invested": 148050,
      "status": "sl",
      "pnlPct": -4.51,
      "exitDate": "17 Aug",
      "exitTs": 1786938300,
      "reason": "SL hit 1885 pe — out, end of story. Sell is a sell.",
      "live": true
    },
    {
      "picked": "11 Aug",
      "ts": 1786419900,
      "symbol": "HESTERBIO",
      "sector": "Healthcare",
      "gear": 3,
      "entry": 2547,
      "status": "no-trigger",
      "pnlPct": 0,
      "exitTs": 1786938300,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "live": true
    },
    {
      "picked": "14 Aug",
      "ts": 1786679100,
      "symbol": "MBAPL",
      "sector": "Agri",
      "gear": 3,
      "entry": 172,
      "qty": 863,
      "invested": 148436,
      "status": "sl",
      "pnlPct": -5.12,
      "exitDate": "18 Aug",
      "exitTs": 1787024700,
      "reason": "SL hit 163.2 pe — out, end of story. Sell is a sell.",
      "live": true
    },
    {
      "picked": "14 Aug",
      "ts": 1786679100,
      "symbol": "KRISHANA",
      "sector": "Agri",
      "gear": 3,
      "entry": 193.9,
      "qty": 766,
      "invested": 148527.4,
      "status": "sl",
      "pnlPct": -4.49,
      "exitDate": "18 Aug",
      "exitTs": 1787024700,
      "reason": "SL hit 185.2 pe — out, end of story. Sell is a sell.",
      "live": true
    },
    {
      "picked": "12 Aug",
      "ts": 1786506300,
      "symbol": "UJJIVANSFB",
      "sector": "Financial Services",
      "gear": 3,
      "entry": 73.3,
      "status": "no-trigger",
      "pnlPct": 0,
      "exitTs": 1787024700,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "live": true
    },
    {
      "picked": "13 Aug",
      "ts": 1786592700,
      "symbol": "EMCURE",
      "sector": "Healthcare",
      "gear": 4,
      "entry": 2048,
      "status": "no-trigger",
      "pnlPct": 0,
      "exitTs": 1787111100,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "live": true
    },
    {
      "picked": "18 Aug",
      "ts": 1787024700,
      "symbol": "DATAPATTNS",
      "sector": "Defence",
      "gear": 3,
      "entry": 4750,
      "status": "no-cash",
      "pnlPct": 0,
      "exitTs": 1787111100,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi (₹5,40,773 deployed) — ye trade chhoot gayi. Cash bhi ek position hai.",
      "live": true
    },
    {
      "picked": "17 Aug",
      "ts": 1786938300,
      "symbol": "BALRAMCHIN",
      "sector": "Agri",
      "gear": 3,
      "entry": 665.5,
      "qty": 109,
      "invested": 72539.5,
      "status": "win",
      "pnlPct": 15.27,
      "exitDate": "20 Aug",
      "exitTs": 1787197500,
      "reason": "+15.27% — double digit aa gaya, 50% book kiya. Baaki 40 DMA pe trail hoga.",
      "live": true
    },
    {
      "picked": "18 Aug",
      "ts": 1787024700,
      "symbol": "UJJIVANSFB",
      "sector": "Financial Services",
      "gear": 3,
      "entry": 73.3,
      "status": "no-cash",
      "pnlPct": 0,
      "exitTs": 1787197500,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi (₹4,68,233 deployed) — ye trade chhoot gayi. Cash bhi ek position hai.",
      "live": true
    },
    {
      "picked": "17 Aug",
      "ts": 1786938300,
      "symbol": "CYIENTDLM",
      "sector": "Defence",
      "gear": 3,
      "entry": 743,
      "qty": 195,
      "invested": 144885,
      "status": "sl",
      "pnlPct": -4.5,
      "exitDate": "21 Aug",
      "exitTs": 1787283900,
      "reason": "SL hit 709.6 pe — out, end of story. Sell is a sell.",
      "live": true
    },
    {
      "picked": "20 Aug",
      "ts": 1787197500,
      "symbol": "GAEL",
      "sector": "Fast Moving Consumer Goods",
      "gear": 3,
      "entry": 184.7,
      "status": "no-cash",
      "pnlPct": 0,
      "exitTs": 1787283900,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi (₹4,69,414 deployed) — ye trade chhoot gayi. Cash bhi ek position hai.",
      "live": true
    },
    {
      "picked": "21 Aug",
      "ts": 1787283900,
      "symbol": "PAYTM",
      "sector": "New Age / Internet",
      "gear": 2,
      "entry": 1658,
      "status": "no-cash",
      "pnlPct": 0,
      "exitTs": 1787629500,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi (₹4,69,414 deployed) — ye trade chhoot gayi. Cash bhi ek position hai.",
      "live": true
    },
    {
      "picked": "20 Aug",
      "ts": 1787197500,
      "symbol": "JKPAPER",
      "sector": "Forest Materials",
      "gear": 3,
      "entry": 398,
      "qty": 367,
      "invested": 146066,
      "status": "fail",
      "pnlPct": -0.36,
      "exitDate": "26 Aug",
      "exitTs": 1787715900,
      "reason": "Breakout fail — 3 din squat, move nahi aaya. Abnormal behavior = out.",
      "live": true
    },
    {
      "picked": "21 Aug",
      "ts": 1787283900,
      "symbol": "DIAMONDYD",
      "sector": "Fast Moving Consumer Goods",
      "gear": 2,
      "entry": 1229,
      "status": "no-trigger",
      "pnlPct": 0,
      "exitTs": 1787802300,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "live": true
    },
    {
      "picked": "25 Aug",
      "ts": 1787629500,
      "symbol": "VENKEYS",
      "sector": "Agri",
      "gear": 3,
      "entry": 1609,
      "status": "no-cash",
      "pnlPct": 0,
      "exitTs": 1787802300,
      "reason": "Breakout to aaya, par capital pehle se lagi hui thi (₹4,67,015 deployed) — ye trade chhoot gayi. Cash bhi ek position hai.",
      "live": true
    },
    {
      "picked": "24 Aug",
      "ts": 1787543100,
      "symbol": "MAHLOG",
      "sector": "Logistics / Shipping",
      "gear": 2,
      "entry": 418.8,
      "status": "no-trigger",
      "pnlPct": 0,
      "exitTs": 1787888700,
      "reason": "Pivot cross nahi hua 4 session me — list se bahar, paisa laga hi nahi",
      "live": true
    },
    {
      "picked": "4 May",
      "ts": 1777866300,
      "symbol": "STYLAMIND",
      "sector": "Consumer Durables",
      "gear": 3,
      "entry": 2268,
      "qty": 16,
      "invested": 36288,
      "status": "win",
      "pnlPct": 47.46,
      "exitDate": "1 Sept",
      "exitTs": 1788234300,
      "reason": "40 DMA trail exit — jo mila le liya",
      "live": true
    },
    {
      "picked": "18 Jun",
      "ts": 1781754300,
      "symbol": "ANANDRATHI",
      "sector": "Financial Services",
      "gear": 5,
      "entry": 1857,
      "qty": 38,
      "invested": 70566,
      "status": "open",
      "pnlPct": 18.31,
      "reason": "Open — entry 1857, SL 1773, partial book zone me hai"
    },
    {
      "picked": "23 Jun",
      "ts": 1782186300,
      "symbol": "WELCORP",
      "sector": "Capital Goods",
      "gear": 2,
      "entry": 1439,
      "qty": 50,
      "invested": 71950,
      "status": "open",
      "pnlPct": 77.46,
      "reason": "Open — entry 1439, SL 1374, partial book zone me hai"
    },
    {
      "picked": "2 Jul",
      "ts": 1782963900,
      "symbol": "AKUMS",
      "sector": "Healthcare",
      "gear": 4,
      "entry": 642.9,
      "qty": 112,
      "invested": 72004.8,
      "status": "open",
      "pnlPct": 21.18,
      "reason": "Open — entry 642.9, SL 614, partial book zone me hai"
    },
    {
      "picked": "17 Aug",
      "ts": 1786938300,
      "symbol": "BALRAMCHIN",
      "sector": "Agri",
      "gear": 3,
      "entry": 665.5,
      "qty": 109,
      "invested": 72539.5,
      "status": "open",
      "pnlPct": 0.5,
      "reason": "Open — entry 665.5, SL 635.6"
    },
    {
      "picked": "24 Aug",
      "ts": 1787543100,
      "symbol": "NAVINFLUOR",
      "sector": "Chemicals",
      "gear": 2,
      "entry": 8451,
      "qty": 17,
      "invested": 143667,
      "status": "open",
      "pnlPct": 2.19,
      "reason": "Open — entry 8451, SL 8110"
    }
  ]
};
