// AUTO-GENERATED by scripts/scan.mjs — haath se edit mat karo
window.DASHBOARD_DATA = {
  "demo": false,
  "generatedAt": "Monday, 6 July 2026 · 08:29 pm IST",
  "sessionDate": "06/07/2026",
  "nextTradingDay": "Tuesday, 7 July 2026",
  "portfolio": {
    "startCapital": 100000,
    "sizingRule": "Gear-based: 1st gear 10% → 5th gear 25% of capital",
    "sizeByGear": [
      10,
      14,
      17,
      21,
      25
    ]
  },
  "market": {
    "gear": 3,
    "gearLabel": "3rd Gear",
    "verdict": "Market me traction hai — test trades chal rahi hain, easiness aa rahi hai. Size badha sakte ho, lekin 5th gear abhi nahi. Aaj ke breakouts ka behavior hi kal ka thermometer hai.",
    "checks": [
      {
        "label": "CNX Smallcap vs 50 DMA",
        "status": "warn",
        "note": "50 DMA ke upar (8 din se hold), lekin 50 DMA flat/declining"
      },
      {
        "label": "10 DMA",
        "status": "good",
        "note": "Index 10 DMA ke upar — first signs of strength"
      },
      {
        "label": "Breakouts working?",
        "status": "warn",
        "note": "35% me traction (56 traction, 74 flat, 29 fail) — selective/mixed, size control me rakho"
      },
      {
        "label": "Breadth (50 DMA ke upar)",
        "status": "good",
        "note": "64% universe 50 DMA ke upar"
      },
      {
        "label": "Advance / Decline",
        "status": "warn",
        "note": "361 advances vs 384 declines aaj"
      },
      {
        "label": "52W high zone",
        "status": "good",
        "note": "76 stocks 52W-high zone me, 24 low zone me"
      },
      {
        "label": "USDINR",
        "status": "warn",
        "note": "USDINR +1.16% in 10 din — rupaya gir raha hai, alarm"
      }
    ]
  },
  "hotSectors": [
    {
      "name": "Realty",
      "note": "5 din me avg +7.06% · 12/16 stocks me lagatar action · volumes badhe hue"
    },
    {
      "name": "Agri",
      "note": "5 din me avg +7.6% · 2/3 stocks me lagatar action"
    },
    {
      "name": "Diversified",
      "note": "5 din me avg +4.94% · 3/4 stocks me lagatar action · volumes badhe hue"
    },
    {
      "name": "New Age / Internet",
      "note": "5 din me avg +5.68% · 4/6 stocks me lagatar action · volumes badhe hue"
    }
  ],
  "picks": [
    {
      "symbol": "BALRAMCHIN",
      "name": "Balrampur Chini",
      "sector": "Agri",
      "cap": "Small",
      "cmp": 571,
      "pivot": 576,
      "entry": "576 ke upar close/cross, elevated volume ke saath",
      "sl": 550.1,
      "slPct": 4.5,
      "target": "627.8 – 643.3",
      "rr": "1 : 2.3",
      "setup": "Tight base — 15 din, 9.28% range, pivot ke paas",
      "volumeNote": "Volume abhi normal hai — breakout pe elevated chahiye.",
      "comment": "Base bana hua hai, 9.28% range me pivot ke paas trade ho raha hai. Agri sector me in dino nonstop action hai — money flow yahi hai. 52-week high zone me hai — upar supply nahi, line of least resistance upar. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        540,
        551.6,
        559,
        546.9,
        554.2,
        531.6,
        536.6,
        532.9,
        536.8,
        534.2,
        534.2,
        527.1,
        555,
        545.8,
        567.2,
        562.5,
        571
      ],
      "flags": [
        "Hot sector",
        "Tight base",
        "52W high zone",
        "5% stock"
      ],
      "detail": {
        "dma10": 546.7,
        "dma20": 545.4,
        "dma50": 536.7,
        "dma50Rising": true,
        "dist52w": 9.95,
        "hi52": 627.8,
        "tradedValueCr": 27.11,
        "volRatio": 1.32,
        "rangePct": 9.28,
        "baseDays": 15,
        "proxPivot": 0.88,
        "atrRatio": 1.07,
        "bigMoveDays": 12,
        "t1": 627.8,
        "t2": 643.3
      }
    },
    {
      "symbol": "SAILIFE",
      "name": "Sai Life Sciences",
      "sector": "Healthcare",
      "cap": "Small",
      "cmp": 1233,
      "pivot": 1260,
      "entry": "1260 ke upar close/cross, elevated volume ke saath",
      "sl": 1203,
      "slPct": 4.52,
      "target": "1374 – 1408",
      "rr": "1 : 2.3",
      "setup": "Super tight consolidation — 15 din, 6.38% range",
      "volumeNote": "Base me volume shrink — classic supply exhaustion.",
      "comment": "15 din se super tight consolidation hai (6.38% range) — jitna zyada consolidate hua, utna achha action on the breakout. 52-week high zone me hai — upar supply nahi, line of least resistance upar. base me volume shrink — supply exhaust ho rahi hai. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        1218,
        1208,
        1206,
        1214,
        1207,
        1216,
        1202,
        1218,
        1205,
        1221,
        1221,
        1248,
        1234,
        1244,
        1238,
        1257,
        1233
      ],
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "detail": {
        "dma10": 1232,
        "dma20": 1219,
        "dma50": 1158,
        "dma50Rising": true,
        "dist52w": 2.22,
        "hi52": 1260,
        "tradedValueCr": 53.46,
        "volRatio": 0.74,
        "rangePct": 6.38,
        "baseDays": 15,
        "proxPivot": 2.22,
        "atrRatio": 0.79,
        "bigMoveDays": 5,
        "t1": 1374,
        "t2": 1408
      }
    },
    {
      "symbol": "NAVINFLUOR",
      "name": "Navin Fluorine",
      "sector": "Chemicals",
      "cap": "Small",
      "cmp": 7729,
      "pivot": 7810,
      "entry": "7810 ke upar close/cross, elevated volume ke saath",
      "sl": 7459,
      "slPct": 4.49,
      "target": "8512 – 8723",
      "rr": "1 : 2.3",
      "setup": "Tight base — 15 din, 8.35% range, pivot ke paas",
      "volumeNote": "Base me volume shrink — classic supply exhaustion.",
      "comment": "Base bana hua hai, 8.35% range me pivot ke paas trade ho raha hai. 52-week high zone me hai — upar supply nahi, line of least resistance upar. base me volume shrink — supply exhaust ho rahi hai. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        7303,
        7287,
        7316,
        7344,
        7304,
        7494,
        7572,
        7501,
        7699,
        7609,
        7609,
        7487,
        7687,
        7585,
        7647,
        7553,
        7729
      ],
      "flags": [
        "Tight base",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "detail": {
        "dma10": 7610,
        "dma20": 7438,
        "dma50": 7188,
        "dma50Rising": true,
        "dist52w": 1.05,
        "hi52": 7810,
        "tradedValueCr": 104.12,
        "volRatio": 0.96,
        "rangePct": 8.35,
        "baseDays": 15,
        "proxPivot": 1.05,
        "atrRatio": 0.95,
        "bigMoveDays": 3,
        "t1": 8512,
        "t2": 8723
      }
    },
    {
      "symbol": "STAR",
      "name": "Strides Pharma Science",
      "sector": "Healthcare",
      "cap": "Micro",
      "cmp": 1122,
      "pivot": 1150,
      "entry": "1150 ke upar close/cross, elevated volume ke saath",
      "sl": 1098,
      "slPct": 4.51,
      "target": "1253 – 1284",
      "rr": "1 : 2.29",
      "setup": "Super tight consolidation — 15 din, 7.01% range",
      "volumeNote": "Base me volume shrink — classic supply exhaustion.",
      "comment": "15 din se super tight consolidation hai (7.01% range) — jitna zyada consolidate hua, utna achha action on the breakout. 52-week high zone me hai — upar supply nahi, line of least resistance upar. base me volume shrink — supply exhaust ho rahi hai. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        1056,
        1085,
        1103,
        1107,
        1111,
        1111,
        1116,
        1111,
        1111,
        1082,
        1082,
        1103,
        1093,
        1094,
        1126,
        1127,
        1122
      ],
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "detail": {
        "dma10": 1105,
        "dma20": 1086,
        "dma50": 1100,
        "dma50Rising": true,
        "dist52w": 9.75,
        "hi52": 1231,
        "tradedValueCr": 18.63,
        "volRatio": 0.75,
        "rangePct": 7.01,
        "baseDays": 15,
        "proxPivot": 2.51,
        "atrRatio": 0.82,
        "bigMoveDays": 13,
        "t1": 1253,
        "t2": 1284
      }
    },
    {
      "symbol": "GRASIM",
      "name": "Grasim Industries",
      "sector": "Construction Materials",
      "cap": "Large",
      "cmp": 3213,
      "pivot": 3219,
      "entry": "3219 ke upar close/cross, elevated volume ke saath",
      "sl": 3074,
      "slPct": 4.51,
      "target": "3510 – 3597",
      "rr": "1 : 2.3",
      "setup": "Super tight consolidation — 15 din, 4.58% range",
      "volumeNote": "Base me volume shrink — classic supply exhaustion.",
      "comment": "15 din se super tight consolidation hai (4.58% range) — jitna zyada consolidate hua, utna achha action on the breakout. 52-week high zone me hai — upar supply nahi, line of least resistance upar. base me volume shrink — supply exhaust ho rahi hai. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        3106,
        3165,
        3140,
        3150,
        3145,
        3150,
        3175,
        3144,
        3128,
        3127,
        3127,
        3080,
        3100,
        3140,
        3169,
        3181,
        3213
      ],
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone"
      ],
      "detail": {
        "dma10": 3141,
        "dma20": 3135,
        "dma50": 3053,
        "dma50Rising": true,
        "dist52w": 0.2,
        "hi52": 3219,
        "tradedValueCr": 191.96,
        "volRatio": 0.85,
        "rangePct": 4.58,
        "baseDays": 15,
        "proxPivot": 0.2,
        "atrRatio": 0.88,
        "bigMoveDays": 1,
        "t1": 3510,
        "t2": 3597
      }
    }
  ],
  "journal": [
    {
      "picked": "3 Jul",
      "symbol": "ZYDUSLIFE",
      "sector": "Pharma",
      "gear": 4,
      "entry": 1145,
      "status": "open",
      "pnlPct": 0,
      "reason": "Open — entry 1145, SL 1095"
    }
  ]
};
