// AUTO-GENERATED by scripts/scan.mjs — haath se edit mat karo
window.DASHBOARD_DATA = {
  "demo": false,
  "generatedAt": "Tuesday, 7 July 2026 · 12:26 am IST",
  "sessionDate": "03/07/2026",
  "nextTradingDay": "Monday, 6 July 2026",
  "portfolio": {
    "startCapital": 100000,
    "sizingRule": "Gear-based: 1st gear 10% → 5th gear 25% of capital",
    "sizeByGear": [
      10,
      14,
      17,
      21,
      25
    ]
  },
  "market": {
    "gear": 3,
    "gearLabel": "3rd Gear",
    "verdict": "Market me traction hai — test trades chal rahi hain, easiness aa rahi hai. Size badha sakte ho, lekin 5th gear abhi nahi. Aaj ke breakouts ka behavior hi kal ka thermometer hai.",
    "checks": [
      {
        "label": "CNX Smallcap vs 50 DMA",
        "status": "warn",
        "note": "50 DMA ke upar (7 din se hold), lekin 50 DMA flat/declining"
      },
      {
        "label": "10 DMA",
        "status": "good",
        "note": "Index 10 DMA ke upar — first signs of strength"
      },
      {
        "label": "Breakouts working?",
        "status": "warn",
        "note": "33% me traction (52 traction, 79 flat, 25 fail) — selective/mixed, size control me rakho"
      },
      {
        "label": "Breadth (50 DMA ke upar)",
        "status": "good",
        "note": "65% universe 50 DMA ke upar"
      },
      {
        "label": "Advance / Decline",
        "status": "warn",
        "note": "350 advances vs 395 declines aaj"
      },
      {
        "label": "52W high zone",
        "status": "good",
        "note": "76 stocks 52W-high zone me, 27 low zone me"
      },
      {
        "label": "USDINR",
        "status": "warn",
        "note": "USDINR +1.12% in 10 din — rupaya gir raha hai, alarm"
      }
    ]
  },
  "hotSectors": [
    {
      "name": "New Age / Internet",
      "note": "5 din me avg +5.46% · 4/6 stocks me lagatar action · volumes badhe hue"
    },
    {
      "name": "Diversified",
      "note": "5 din me avg +3.41% · 4/4 stocks me lagatar action · volumes badhe hue"
    },
    {
      "name": "Realty",
      "note": "5 din me avg +4.52% · 12/16 stocks me lagatar action · volumes badhe hue"
    },
    {
      "name": "Agri",
      "note": "5 din me avg +3.28% · 2/3 stocks me lagatar action · volumes badhe hue"
    }
  ],
  "picks": [
    {
      "symbol": "SAILIFE",
      "name": "Sai Life Sciences",
      "sector": "Healthcare",
      "cap": "Small",
      "cmp": 1257,
      "pivot": 1260,
      "entry": "1260 ke upar close/cross, elevated volume ke saath",
      "sl": 1203,
      "slPct": 4.52,
      "target": "1374 – 1408",
      "rr": "1 : 2.3",
      "setup": "Super tight consolidation — 15 din, 6.26% range",
      "volumeNote": "Volume abhi normal hai — breakout pe elevated chahiye.",
      "comment": "15 din se super tight consolidation hai (6.26% range) — jitna zyada consolidate hua, utna achha action on the breakout. 52-week high zone me hai — upar supply nahi, line of least resistance upar. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        1181,
        1218,
        1208,
        1206,
        1214,
        1207,
        1216,
        1202,
        1218,
        1205,
        1221,
        1221,
        1248,
        1234,
        1244,
        1238,
        1257
      ],
      "flags": [
        "Super tight",
        "52W high zone",
        "5% stock"
      ],
      "detail": {
        "dma10": 1229,
        "dma20": 1218,
        "dma50": 1155,
        "dma50Rising": true,
        "dist52w": 0.21,
        "hi52": 1260,
        "tradedValueCr": 55.07,
        "volRatio": 1.14,
        "rangePct": 6.26,
        "baseDays": 15,
        "proxPivot": 0.21,
        "atrRatio": 0.83,
        "bigMoveDays": 5,
        "t1": 1374,
        "t2": 1408
      }
    },
    {
      "symbol": "STAR",
      "name": "Strides Pharma Science",
      "sector": "Healthcare",
      "cap": "Micro",
      "cmp": 1127,
      "pivot": 1150,
      "entry": "1150 ke upar close/cross, elevated volume ke saath",
      "sl": 1098,
      "slPct": 4.51,
      "target": "1253 – 1284",
      "rr": "1 : 2.29",
      "setup": "Super tight consolidation — 15 din, 7.24% range",
      "volumeNote": "Base me volume shrink — classic supply exhaustion.",
      "comment": "15 din se super tight consolidation hai (7.24% range) — jitna zyada consolidate hua, utna achha action on the breakout. 52-week high zone me hai — upar supply nahi, line of least resistance upar. base me volume shrink — supply exhaust ho rahi hai. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        989.2,
        1056,
        1085,
        1103,
        1107,
        1111,
        1111,
        1116,
        1111,
        1111,
        1082,
        1082,
        1103,
        1093,
        1094,
        1126,
        1127
      ],
      "flags": [
        "Super tight",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "detail": {
        "dma10": 1105,
        "dma20": 1080,
        "dma50": 1100,
        "dma50Rising": true,
        "dist52w": 9.25,
        "hi52": 1231,
        "tradedValueCr": 19.52,
        "volRatio": 0.91,
        "rangePct": 7.24,
        "baseDays": 15,
        "proxPivot": 2.04,
        "atrRatio": 0.85,
        "bigMoveDays": 13,
        "t1": 1253,
        "t2": 1284
      }
    },
    {
      "symbol": "YATHARTH",
      "name": "Yatharth Hospital & Trauma Care Services",
      "sector": "Healthcare",
      "cap": "Micro",
      "cmp": 865.5,
      "pivot": 883.4,
      "entry": "883.4 ke upar close/cross, elevated volume ke saath",
      "sl": 843.6,
      "slPct": 4.51,
      "target": "963 – 986.9",
      "rr": "1 : 2.3",
      "setup": "Tight base — 15 din, 7.71% range, pivot ke paas",
      "volumeNote": "Base me volume shrink — classic supply exhaustion.",
      "comment": "Base bana hua hai, 7.71% range me pivot ke paas trade ho raha hai. 52-week high zone me hai — upar supply nahi, line of least resistance upar. base me volume shrink — supply exhaust ho rahi hai. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        825.8,
        839.8,
        829.4,
        828.2,
        821.4,
        845.2,
        839.8,
        851.9,
        853.3,
        857,
        837,
        837,
        848.9,
        858.6,
        856.8,
        862.6,
        865.5
      ],
      "flags": [
        "Tight base",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "detail": {
        "dma10": 852.9,
        "dma20": 842.2,
        "dma50": 828.6,
        "dma50Rising": true,
        "dist52w": 2.81,
        "hi52": 889.9,
        "tradedValueCr": 26.58,
        "volRatio": 0.99,
        "rangePct": 7.71,
        "baseDays": 15,
        "proxPivot": 2.06,
        "atrRatio": 0.89,
        "bigMoveDays": 13,
        "t1": 963,
        "t2": 986.9
      }
    },
    {
      "symbol": "ANANTRAJ",
      "name": "Anant Raj",
      "sector": "Realty",
      "cap": "Small",
      "cmp": 554.7,
      "pivot": 556.8,
      "entry": "556.8 ke upar close/cross, elevated volume ke saath",
      "sl": 531.7,
      "slPct": 4.5,
      "target": "606.8 – 621.9",
      "rr": "1 : 2.3",
      "setup": "Tight base — 15 din, 8.2% range, pivot ke paas",
      "volumeNote": "Volume abhi normal hai — breakout pe elevated chahiye.",
      "comment": "Base bana hua hai, 8.2% range me pivot ke paas trade ho raha hai. Realty sector me in dino nonstop action hai — money flow yahi hai. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        513.3,
        534.8,
        537.3,
        540.7,
        530.9,
        528.8,
        520.2,
        532.3,
        522.8,
        528.6,
        522.5,
        522.5,
        513.8,
        521.3,
        516.9,
        537.7,
        554.7
      ],
      "flags": [
        "Hot sector",
        "Tight base",
        "5% stock"
      ],
      "detail": {
        "dma10": 527.3,
        "dma20": 528.8,
        "dma50": 521.3,
        "dma50Rising": true,
        "dist52w": 34.06,
        "hi52": 743.7,
        "tradedValueCr": 92.21,
        "volRatio": 1.02,
        "rangePct": 8.2,
        "baseDays": 15,
        "proxPivot": 0.37,
        "atrRatio": 1.25,
        "bigMoveDays": 10,
        "t1": 606.8,
        "t2": 621.9
      }
    },
    {
      "symbol": "SFL",
      "name": "Sheela Foam",
      "sector": "Consumer Durables",
      "cap": "Micro",
      "cmp": 766.5,
      "pivot": 770,
      "entry": "770 ke upar close/cross, elevated volume ke saath",
      "sl": 735.4,
      "slPct": 4.49,
      "target": "839.2 – 860",
      "rr": "1 : 2.3",
      "setup": "Tight base — 15 din, 10.01% range, pivot ke paas",
      "volumeNote": "Base me volume shrink — classic supply exhaustion.",
      "comment": "Base bana hua hai, 10.01% range me pivot ke paas trade ho raha hai. 52-week high zone me hai — upar supply nahi, line of least resistance upar. base me volume shrink — supply exhaust ho rahi hai. Breakout aaye tabhi entry bhaiya — usse pehle jo bhi hai, sirf indication hai.",
      "spark": [
        680.3,
        703.5,
        709.6,
        703.5,
        709.8,
        702.5,
        700.7,
        741.8,
        736.3,
        734.8,
        725.6,
        725.6,
        742.7,
        746.9,
        736.9,
        763,
        766.5
      ],
      "flags": [
        "Tight base",
        "Volume shrink",
        "52W high zone",
        "5% stock"
      ],
      "detail": {
        "dma10": 742,
        "dma20": 718.9,
        "dma50": 634.5,
        "dma50Rising": true,
        "dist52w": 0.45,
        "hi52": 770,
        "tradedValueCr": 21.21,
        "volRatio": 0.56,
        "rangePct": 10.01,
        "baseDays": 15,
        "proxPivot": 0.45,
        "atrRatio": 1.09,
        "bigMoveDays": 11,
        "t1": 839.2,
        "t2": 860
      }
    }
  ],
  "journal": []
};
